name: 🎙️ Talk Proposal
description: Create a proposal for your talk at PyDelhi Monthly Meetups. 
labels: ["proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share your learnings with the Python Community! We would highly recommend you go through our [guidelines on submitting a proposal and giving a talk](https://github.com/pydelhi/talks/blob/master/guidelines.md), especially if it is your first time. Please note that all talks are licensed under a [Creative Commons Attribution-Non Commercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/).
  - type: input
    id: title
    attributes:
      label: Title
      description: Please share the title of your talk
      placeholder: For E.g, Introduction to Machine Learning with Python
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe your Talk
      description: Brief description about your talk in 50-100 words.
    validations:
      required: true
  - type: textarea
    id: prerequisites
    attributes:
      label: Pre-requisites & reading material
      description: Anything that the audience should know/read before the session starts
  - type: textarea
    id: Resources
    attributes:
      label: Resources
      description: Any relevant resources for the reviewer(s) or the audience
  - type: input
    id: time
    attributes:
      label: Time required for the talk 
      description: Please specify how much time does your talk requires (E.g 30 mins, 45 mins etc)
    validations:
      required: true
  - type: input
    id: slides
    attributes:
      label: Link to slides/demos
      description: How can we get in touch with you if we need more info?
      placeholder: ex. https://slides.com/....
    validations:
      required: false
  - type: textarea
    id: about-author
    attributes:
      label: About you
      description: Briefly describe who you are and what you do. Include your socials like Twitter, Facebook.
    validations:
      required: true
  - type: input
    id: availability
    attributes:
      label: Availability
      description: When would you be able to give this talk?
      placeholder: DD/MM/YYYY
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: Any comments
      description: Share any other information that you think is necessary
    validations:
      required: false
