# Mark proposals as inactive after 60 days of inactivity;
# See https://github.com/actions/stale for more on configuration

name: Mark open talk proposals as inactive
on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    - cron: "0 3 15 * *" # 0300 UTC on day 15 of the month
    - cron: "0 3 * * 6" # 0300 UTC on every Saturday
  workflow_dispatch:

concurrency:
  group: "stale-proposals-workflow"
  cancel-in-progress: false

permissions: {}

jobs:
  stale:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          days-before-stale: 60 # corresponds to two months/meetups
          days-before-close: -1 # never close any issues; we'll do this manually.
          stale-issue-label: "inactive"
          remove-stale-when-updated: true
          stale-issue-message: |
            Hi there! This proposal has been automatically marked as "inactive" due to it
            not receiving any activity for the last sixty days.

            To you as a contributor to the PyDelhi community, thank you for your proposal
            and apologies if this issue fell through the cracks! This ping was created to
            help bring this proposal a fresh pair of eyes. If you need any help, you can
            always reach out here on this issue, or email us at
            [pydelhi.org@gmail.com](mailto:pydelhi.org@gmail.com).

            If you think that this talk is no longer relevant, or that you are no longer
            available to deliver this talk at one of our meetups in the coming time, you
            may either close this issue, or the currently active volunteers shall do it
            at some point in the future. If you are still interested in delivering this
            talk, please comment on this issue to indicate your interest, and the
            "inactive" label will be dropped automatically.

            If you are a volunteer for the PyDelhi community, and if you no longer have
            the bandwidth to dedicate to reviewing this proposal, please consider
            reaching out to your fellow volunteers to help you with this proposal on the
            appropriate communication channels.

            If this issue is not a talk proposal, please ignore this message, remove the
            "inactive" label, and either continue with your work here as planned or
            close this issue if it is no longer relevant.
